name: Claude Code

on:
  issue_comment:
    types: [created]           # add edited if you want edits to trigger
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]  # add edited if you want edits to trigger
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write     # was read
      issues: write            # was read
      actions: read
      # id-token: write        # only if you really need OIDC

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Project Setup
        run: |
          npm ci
          # run your daemon in background so the step returns:
          nohup npm run dev:daemon > logs.txt 2>&1 & echo $! > /tmp/dev.pid || true

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          prompt: |
            The project is already set up with all dependencies installed.
            The server is running at http://localhost:3000 and logs to logs.txt.
            You can use sqlite3 for DB queries and Playwright MCP to drive the app.

          claude_args: |
            --model claude-3-5-sonnet-20241022
            --mcp-config-json '{"mcpServers":{"playwright":{"command":"npx","args":["@microsoft/playwright-mcp@latest"]}}}'
            --allowed-tools Bash(npm:*),Bash(sqlite3:*),mcp__playwright__browser_snapshot,mcp__playwright__browser_click,mcp__playwright__browser_fill,mcp__playwright__browser_navigate,mcp__playwright__browser_assert

          additional_permissions: |
            actions: read